---

- hosts: all
  become: true
  tasks:

          - name: install apache2 package and php packages for Ubuntu
            apt:
                    name: 
                        - apache2
                        - libapache2-mod-php
                    state: latest
            when: ansible_distribution == "Ubuntu"
#           when: ansible_distribution in ["CentOS", "Ubuntu"]
