---

- hosts: all
  become: true
  tasks:
          - name: install updates (CentOS)
            yum:
                    update_only: yes
                    update_cache: yes
            when: ansible_distribution == "CentOS"

          - name: install updates (Ubuntu)
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

          - name: install apache and php packages for Ubuntu
            apt:
                    name: 
                        - apache2
                        - libapache2-mod-php
                    state: latest

            when: ansible_distribution == "Ubuntu"
#           when: ansible_distribution in ["CentOS", "Ubuntu"]
        
          - name: install apache and php packages for CentOS
            yum:
                    name:
                        - httpd
                        - php
                    state: latest
            when: ansible_distribution == "CentOS"
