---

- hosts: all
  become: true
  tasks:
          - name: install updates (CentOS)
            tags: always
            yum:
                    update_only: yes
                    update_cache: yes
            when: ansible_distribution == "CentOS"

          - name: install updates (Ubuntu)
            tags: always
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

          - name: install apache and php packages for Ubuntu
            tags: ubuntu,apache,apache2,php
            apt:
                    name: 
                        - apache2
                        - libapache2-mod-php
                    state: latest

            when: ansible_distribution == "Ubuntu"
#           when: ansible_distribution in ["CentOS", "Ubuntu"]
        
          - name: install apache and php packages for CentOS
            tags: centos,apache,httpd,php
            yum:
                    name:
                        - httpd
                        - php
                    state: latest
            when: ansible_distribution == "CentOS"

          - name: start httpd
            tags: apache,centos,httpd
            service:
                    name: httpd
                    state: started
                    enabled: yes
            when: ansible_distribution == "CentOS"

          - name: copy defualt html file for site
            tags: apache,apache2,httpd,html
            copy:
                    src: default_site.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644

- hosts: db_servers
  become: true
  tasks:
          - name: install mariadb package (CentOS)
            tags: db,mariadb,centos
            yum:
                    name: mariadb
                    state: latest
            when: ansible_distribution == "CentOS"

          - name: install mariadb package (Ubuntu)
            tags: db,mariadb,ubuntu
            apt:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == "Ubuntu"

